#:schema node_modules/wrangler/config-schema.json
name = "remix-d1"
compatibility_date = "2024-06-10"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "remix-d1-local"
database_id = "d96d3905-cc50-4bec-bca2-523925b92c88"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "remix-d1-preview"
database_id = "aa19e296-3db6-421c-beda-bff6e5c4ef71"

[[env.production.d1_databases]]
binding = "DB"
database_name = "remix-d1-prod"
database_id = "7a2954a7-3355-4b63-82a8-1415197ee7cd"
